name: Project build and test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: sudo apt-get update && sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo curl nasm grub-common qemu qemu-kvm mtools
      - name: Get cross compiler
        id: cache-cross
        uses: actions/cache@v1
        with:
          path: cross
          key: cross-compiler
      - name: Build cross compiler
        if: steps.cache-cross.outputs.cache-hit != 'true'
        run: sh run cross -y
      - name: Build
        run: sh run build -y
      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: disk-img
          path: build/disk.img
